spring:
  profiles: default
  
devguide:
  greeting: "안녕하세요"

---

spring:
  profiles: stage

devguide:
  greeting: "스테이징입니다!"

---

spring:
  profiles: dev

devguide:
  greeting: "개발환경입니다!"

---

spring:
  profiles: local

devguide:
  greeting: "당신의PC."
